### ISSUE TITLE
Neleidžia instaliuoti modulio

### ISSUE THREAD

**Issue by bagusislukas** [venipak/Venipak-Prestashop-1.6-1.7.7#26]
Parsisiuntus neleidžia instaliuoti modulio iš .zip failo

**Comment by gadnis** [comment]
@bagusislukas isarchyvuok failą ir suarchyvuok aplanką `mijoravenipak`. Tada įkelk naujai suarchyvuotą zip'ą.

**Comment by Laimonas-Mituzas** [comment]
Didžiajai masei naudotojų reikia pateikti normalaiai sutvarkytą zip failą ir nuorodą į jį. Žmones nesupranta ir nežino tokių dalykų. Tokio paprasto dalyko nepadarymas padidina tik užklausų į supportą keikį.

**Comment by gadnis** [comment]
@Laimonas-Mituzas aš nesu modulio kūrėjas 😁  tik paaiškinau žmogui, nes mačiau, kad galiu.

**Comment by Laimonas-Mituzas** [comment]
> @Laimonas-Mituzas aš nesu modulio kūrėjas 😁 tik paaiškinau žmogui, nes mačiau, kad galiu.

Na kaip ir ne jums teisiogiai žinutė buvo adresuota. Tikiuosi kūrėjai ją taip pat pamatys.

**Comment by modex9** [comment]
Pridėtas release, kuriame modulis supakauotas ir pavadintas taip, kad būtų iš karto tinkamas diegimui: https://github.com/venipak/Venipak-Prestashop-1.6-1.7.7/releases/latest

Taip pat atnaujintas README failas ir jame pateikta atnaujinta diegimo informacija.

**Comment by bagusislukas** [comment]
Chebra 😂 vis tiek kažkas, kažkaip nelabai nori veikti. Pasirinkus
paštomatą bei patvirtinus ir paspaudus tęsti išmeta, jog reikia pasirinkti
terminalą.

2021-11-26, pn 14:56, Modestas Slivinskas ***@***.***> rašė:
