### ISSUE TITLE
 Please select a terminal. 

### ISSUE THREAD

**Issue by bagusislukas** [venipak/Venipak-Prestashop-1.6-1.7.7#28]
![image](https://user-images.githubusercontent.com/42737251/144857809-edfef116-c941-46ab-bc3c-43959503423b.png)

Pasirinktus paštomatą, atsiėmimo punktą neleidžia tęsti link apmokėjimo - galbūt klaida tik pas mane? Nors įdiegiau naujausią modulį iš jūsų.

**Comment by bagusislukas** [comment]
Pridedu dar tinklapio nuorodą - dbaltics.com

**Comment by bagusislukas** [comment]
Atnaujinus modulį problema vis tiek išlikus.

**Comment by modex9** [comment]
Sveiki, pažiūrėjau jūsų svetainėje, problemos neatkartoju
![image](https://user-images.githubusercontent.com/20166429/146517118-5fd82ecf-68e2-4500-a9de-277afcee1daa.png)

 Jeigu vis dar turite problemą, arba kitų klausimų, parašykit į support@mijora.lt.
