### ISSUE TITLE
Questions: live info about parcel on request

### ISSUE THREAD

**Issue by gadnis** [venipak/Venipak-Prestashop-1.6-1.7.7#29]
1. Does your module has feature to check parcel information on venipak api about delivery status?
2. Does your module automatically change order delivery state to `delivered` from venipak api?

If none of these questions has answer "yes":
3. Does venipak api has end point to check parcel delivery status?

if 3 = 'yes'
4. Do you have plans to make this missing great feature? 😁

**Comment by modex9** [comment]
1. Yes, there is shipment tracking functionality in the module: https://i.imgur.com/8jTdwXS.png
2. No.
I will go ahead and answer the remaining questions, despite answering "Yes" to the first one.
3. Yes.
4. Venipak API has the endpoint, which provides the tracking information. However, there is no option to provide a callback URL to a shop, through which API would send information, whenever shipment is delivered. It would be possible to add CRON job, which could check the shipment status periodically, but the process would still be only semi-automatic, i.e the order status would not be updated immediately. So to answer the question, the 3rd condition is not sufficient to make fully automatic order status updates. We do not have any feature plans for this module in the nearest future.

**Comment by modex9** [comment]
Here you go: https://documenter.getpostman.com/view/12497207/TVYCC1o1#8298d390-e05e-43f7-8750-0f0e414f0895
