### ISSUE TITLE
Upgrade request

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [venipak/Venipak-Prestashop-1.6-1.7.7#30]
Module installs two carriers:
Venipak courier and Venipak pickup point. Venipak pickup point carrier allows the buyer to slelect shiiping destination to Pickup point or to Lockers. Whats is great.
Problem: Lockers are phisically restricted by max dimennsions for pracels, but Pickup points not. In carrier settings we set max sizes. So, if the parcel is larger than locker sizes, than the buyer ha no possbillity to choose locker, but also he has no possibillity to choose a pickup point. What is not good.
Solution: to separate pickup point carrier and lockers carrier. In the end we will have 3 carriers and more flexibillity.
Thanks

**Comment by modex9** [comment]
We will pass your suggestion to Venipak. The problem with this solution, is that it would require major overhaul to use two carriers with separate maps, mostly do to structure of map library that was used for this module. 

The actual solution would be to use max height, length and width of pickup points/lockers (which API returns) to filter the suitable delivery points for a cart. Unfortunately, it was decided to not proceed with such feature during module's development, considering the relatively small number of shop owners that actually put in the dimensions for products.
