### ISSUE TITLE
Contribution question

### ISSUE THREAD

**Issue by gadnis** [venipak/Venipak-Prestashop-1.6-1.7.7#32]
Hi,

could you provide some help how could I contribute for the module? I mean, I know how to clone and contribute for git repo, but with your repo I have an issue that a prestashop module lives in a subfolder of your git repo and I don't know how could I clone only the prestashop module folder.

Thanks in advance. P.S. You can write in lithuanian if it's your native language.

**Comment by modex9** [comment]
Sveiki,

Repozitorija nebuvo teisingai struktūrizuota modulio kūrimui. Dabar pakeičiau jos struktūrą ir jūsų minėtos problemos nebeturėtų būti.
