### ISSUE TITLE
getByCartId() error

### ISSUE THREAD

**Issue by Laimonas-Mituzas** [venipak/Venipak-Prestashop-1.6-1.7.7#38]
I have got an error in home page

Fatal error: Uncaught Error: Call to undefined method Order::getByCartId() in /home/pegelt/domains/testas.pege.lt/public_html/modules/mijoravenipak/mijoravenipak.php:515 Stack trace: #0 /home/pegelt/domains/testas.pege.lt/public_html/classes/Cart.php(3019): MijoraVenipak->getOrderShippingCost(Object(Cart), 0) #1 /home/pegelt/domains/testas.pege.lt/public_html/classes/Carrier.php(661): CartCore->getPackageShippingCost(81, true, Object(Country), NULL, '1') #2 /home/pegelt/domains/testas.pege.lt/public_html/classes/Carrier.php(1360): CarrierCore::getCarriersForOrder('1', Array, Object(Cart), Array) #3 /home/pegelt/domains/testas.pege.lt/public_html/classes/Cart.php(1863): CarrierCore::getAvailableCarrierList(Object(Product), 0, 0, 1, Object(Cart)) #4 /home/pegelt/domains/testas.pege.lt/public_html/classes/Cart.php(2073): CartCore->getPackageList(false) #5 /home/pegelt/domains/testas.pege.lt/public_html/classes/Cart.php(2595): CartCore->getDeliveryOptionList(NULL) #6 /home/pegelt/domains/testas.pege.lt/public_html/classes/Car in /home/pegelt/domains/testas.pege.lt/public_html/modules/mijoravenipak/mijoravenipak.php on line 515

PS 1.6.1.17, php 7.1
Venipak module version: last
PS 1.6 does not have method Order::getByCartId(), I coudn't find it via search.

**Comment by modex9** [comment]
Hello,

Thanks for raising issue. I was aware of this problem, but it seems that fix got lost in the trenches.

It is now fixed in the lastest 1.1.1 release.
